
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: demo
            uri: http://localhost:5959
            filters:
              - StripPrefix=1
            predicates:
              - Path=/demo/**

          - id: task-service
            uri: http://localhost:8082
            filters:
              - StripPrefix=1
            predicates:
                - Path=/task-service/**

server:
  port: 7552
eureka:
  client:
    register-with-eureka: false
